never-gonna-give-you-up/README.md
never-gonna-give-you-up/never-gonna-give-you-up.js
never-gonna-give-you-up/never-gonna-give-you-up.test.js
never-gonna-give-you-up/package.json
templates.json

Basic Play demo but why not use it to rick-roll the people a bit? :) 

feat(template): add new play template

---

chat-token/.env
chat-token/README.md
chat-token/functions/token.js
chat-token/package.json
chat-token/tests/token.test.js
never-gonna-give-you-up/tests/never-gonna-give-you-up.test.js
sync-token/.env
sync-token/README.md
sync-token/functions/token.js
sync-token/package.json
sync-token/tests/token.test.js
templates.json
test/test-helper.js
video-token/.env
video-token/README.md
video-token/functions/token.js
video-token/package.json
video-token/tests/token.test.js

This adds some basic token function templates for
- Sync
- Video
- Chat
The next step would be to also create templates for full on applications. But I wanted to provide the ability to also just create token templates.

feat(templates): add video,chat &sync token templates

---

hello-messaging/README.md
hello-messaging/functions/hello-messaging.js
hello-messaging/package.json
hello-messaging/tests/hello-messaging.test.js
hello-voice/README.md
hello-voice/functions/hello-voice.js
hello-voice/package.json
hello-voice/tests/hello-voice.test.js
templates.json

Adds the basic Voice and Messaging templates from the Twilio Console. 

feat(templates): add basic messaging & voice templates

---

http-redirect/.env
http-redirect/README.md
http-redirect/functions/redirect.js
http-redirect/package.json
http-redirect/tests/redirect.test.js
templates.json

Ported from the templates of the Twilio Console. The tests are missing because it's depending on the test helpers in #25 

feat(templates): add http-redirect template

---

README.md

docs(readme): update README with Temp Storage function description

---

.github/config.yml

This enables the Welcome Probot to the project. It has already been installed for the organization.

chore: add welcome probot

---

forward-message-sendgrid/README.md

Updated SendGrid url to use secure link to be inline with other secure links. I verified the secure link works.

Updated SendGrid url to use secure link

---

blacklist-call/.env
blacklist-call/README.md
blacklist-call/functions/blacklist-call.js
blacklist-call/test/blacklist-call.test.js
templates.json

Create a blacklist function template.
Bumps #49 
- [ x ] I acknowledge that all my contributions will be made under the project's license.

#49 blacklist calls template

---

.github/config.yml

Fix grammatical typos in config.yml

docs(config.yml): Fix grammatical typos in config.yml

---

README.md
chat-token/README.md
forward-message-sendgrid/README.md
forward-message-sparkpost/README.md
sync-token/README.md
video-token/README.md

docs(readme): Fix grammar error and typo in READMEs

---

CODE_OF_CONDUCT.md
blacklist-call/README.md

Documentation updates

---

verify/README.md

Documentation updates to make use of the CLI and serverless toolkit better.

docs(readme) update verify function initiation instructions

---

.gitignore
templates.json
voice-client-javascript/.env
voice-client-javascript/README.md
voice-client-javascript/assets/index.html
voice-client-javascript/assets/quickstart.js
voice-client-javascript/assets/site.css
voice-client-javascript/functions/client-voice-twiml-app.js
voice-client-javascript/functions/voice-token.js
voice-client-javascript/package.json
voice-client-javascript/tests/client-voice-twiml-app.test.js
voice-client-javascript/tests/voice-token.test.js

This introduces a Programmable Voice JavaScript Client implementation. It provides a sample JavaScript application ported from [Twilio Client Quickstart](https://www.twilio.com/docs/voice/client/javascript/quickstart)

Voice Client application

---

package.json
templates.json
voicemail/.env
voicemail/README.md
voicemail/functions/recording.js
voicemail/functions/voicemail.js
voicemail/package.json
voicemail/tests/recoding.test.js
voicemail/tests/voicemail.test.js

@philnash can you take a look at this?
I still have to:

feat: add voicemail template

---

docs/CONTRIBUTING.md

Now that there's a better way to test your templates before submitting a PR, I figured we should add that step in the docs.

docs(contributing): add section on testing using the CLI

---

verify/assets/index.html

Adds https://github.com/jackocnr/intl-tel-input for easier phone number inputs.

feat(template/verify): add intl-tel-input

---

verify/functions/start-verify.js

Small change to the server logs for more privacy!

fix(verify): obfuscate phone numbers in logs

---

templates.json

This adds some new templates to the templates.json to expose them to the CLI

chore: expose new templates

---

verify/functions/start-verify.js
verify/package.json

Updates error state with status code returned by Twilio API and sends the error message through to the client.

fix(verify): error message propagation, Twilio dependency for deploy

---

verify/functions/start-verify.js

fix(verify): close string

---

conference-verify/.env
conference-verify/README.md
conference-verify/functions/join-conference.protected.js
conference-verify/functions/verify-conference.protected.js
conference-verify/package.json
conference-verify/tests/join-conference.test.js
conference-verify/tests/verify-conference.test.js
templates.json

This is a port of @robinske excellent blog post to Twilio Functions: https://www.twilio.com/blog/otp-protected-conference-line-verify-python

feat(template): add conference with verification

---

conference-caller-gated/.env
conference-caller-gated/README.md
conference-caller-gated/functions/gated-conference.protected.js
conference-caller-gated/package.json
conference-caller-gated/tests/gated-conference.test.js
conference-pin/.env
conference-pin/README.md
conference-pin/functions/conference-with-pin.protected.js
conference-pin/package.json
conference-pin/tests/conference-with-pin.test.js
templates.json

This PR adds both a gated (only valid phone numbers can join) and a PIN-protected conference line in preparation for the webinar.

Add new conference templates

---

verify/README.md

Fix typo, remove pre-req for console variables
Docs only change

fix (verify): update README.md

---

hunt/package.json

Adds an empty package.json file similar to other templates

fix(hunt): add package.json

---

blocklist-call/package.json
http-redirect/package.json

Create package.json for blocklist-call to conform to the rest of the templates

Create package.json for blocklist-call

---

verify/assets/index.html

Fixes bug in modal submit for index.html asset

fix(verify): prevent duplicate request handlers

---

templates.json
voice-ivr/.env
voice-ivr/README.md
voice-ivr/assets/index.html
voice-ivr/functions/handle-user-input.protected.js
voice-ivr/functions/voice-ivr.protected.js
voice-ivr/package.json
voice-ivr/tests/handle-user-input.test.js
voice-ivr/tests/voice-ivr.test.js

Adds a basic voice IVR tree with three inputs, one of which sends an SMS.

feat(templates): add voice ivr template

---

docs/CONTRIBUTING.md

docs: completed sentence on protected functions.

---

airtable/.env
airtable/README.md
airtable/assets/index.html
blocklist-call/assets/index.html
package-lock.json
voice-client-javascript/package-lock.json
voice-client-javascript/package.json

Adding index pages for 2 apps
- [x ] I ran `npm test` locally and it passed without errors.
- [ x] I acknowledge that all my contributions will be made under the project's [license](../LICENSE).

feat: add index page for blocklist & airtable apps

---

sms-notifications/assets/index.html
sms-notifications/assets/index.js

The phone number UI for the sms-notifications function template now includes an Add button that replicates the functionality of the Enter button for the phone number input. It also now automatically adds the current value of the phone number input (if any) to the recipient list when Send is pressed. 
Resolves #154

fix(sms-notifications): update UI

---

.gitignore
forward-message-mailgun/.env

Adds a .env file for the forward-message-mailgun app.

Add mailgun .env file and update gitignore

---

international-telephone-input/README.md
international-telephone-input/assets/index.html
international-telephone-input/assets/styles.css
international-telephone-input/functions/lookup.js
international-telephone-input/package.json
international-telephone-input/tests/lookup.test.js
templates.json

A mirror of the international telephone input template from main so it can be pulled in via the CLI

Add international telephone input to master branch

---

.github/workflows/nodejs.yml

Adds GitHub Actions as CI for Node.js 10 and 12. Travis has become flaky, slow and expensive since we are on a free tier. We are already paying for GitHub Actions and are running other automations here anyways. I'll remove Travis once this has been successfully merged in.
I left the comments for caching npm dependencies and cypress dependencies for future work.

ci: add github actions tests

---

vaccine-standby/assets/client.js
vaccine-standby/assets/index.html

- Fix UI to render correctly when user submits incorrect admin password
- Add note about updating organization name placeholders in Twilio Studio

fix(vaccine-standby): authentication error UI, editing studio tips

---

_helpers/meta-template/assets/index.html
forward-call/assets/index.html
forward-message-mailgun/assets/index.html
forward-message-multiple/assets/index.html
forward-message-sendgrid/assets/index.html
forward-message-sparkpost/assets/index.html
forward-message/assets/index.html

Adds the `target="_blank" rel="noopener"` attributes to the links in redesigned `index.html` files.

feat(index.html): Add target="_blank" to links

---

segment-event-notification/assets/index.html

Updates the links in the `segment-event-notification` app's `index.html` to include UTM parameters, and adds a link to documentation for the Event Tester.

fix(segment): minor index.html link updates

---

vaccine-standby/README.md

fix(vaccine-standby): fix typo in template name

---

funlet-find-me/functions/funlet-find-me.js
funlet-find-me/tests/funlet-find-me.test.js
vaccine-standby/README.md

This just syncs #207 and #208 into `master`.

fix(funlet-find-me): adjust logic to continue hunting (#207)

---

verify/functions/start-verify.js
verify/tests/start-verify.test.js

Duplicate of #177 to add this to master branch for CLI usage.

feat(verify): disable calls by default

---

_helpers/meta-template/assets/index.html
airtable/assets/index.html
blocklist-call/assets/index.html
conference-caller-gated/assets/index.html
conference-pin/assets/index.html
conference-verify/assets/index.html
conference/assets/index.html
forward-call/assets/index.html
forward-message-mailgun/assets/index.html
forward-message-multiple/assets/index.html
forward-message-sendgrid/assets/index.html
forward-message-sparkpost/assets/index.html
forward-message/assets/index.html
google-sheets/assets/index.html
hello-messaging/assets/index.html

Updates the introduction paragraph copy for each app's `index.html` to "Follow these steps to try out your new app:", which avoids using the word "deployed" and appears a little bit user-friendlier than the previous wording.

feat(index.html): Update intro paragraph copy (batch 1/2)

---

hello-voice/assets/index.html
hello-world/assets/index.html
http-redirect/assets/index.html
hunt/assets/index.html
json-webhook/assets/index.html
masked-number/assets/index.html
never-gonna-give-you-up/assets/index.html
segment-event-notification/assets/index.html
sms-broadcast/assets/index.html
stripe-payment-link-sms/assets/index.html
stripe-sms-receipt/assets/index.html
sync-token/assets/index.html
temp-storage/assets/index.html
video-token/assets/index.html
voicemail/assets/index.html

The second batch of `index.html` copy changes; same change summary as the first batch.

feat(index.html): Update intro paragraph copy (batch 2/2)

---

docs/CONTRIBUTING.md

updates to the readme for contributors
- switch order of `creating pull request` and `testing your template`
- added extra info for env vars
- added steps to deploy & test to hosted twilio serverless environment
see related wiki page: https://wiki.hq.twilio.com/display/MAR/Quick+Deploy+Onboarding+Process

GROW-2622 update readme

---

verify-push-backend/assets/index.html

Small changes to fix response handling and form labeling.

Use identity when destructuring response

---

verify-push-backend/README.md
verify-push-backend/assets/index.html
verify-push-backend/functions/access-token.js
verify-push-backend/functions/challenge-status.js
verify-push-backend/functions/create-challenge.js
verify-push-backend/functions/list-factors.js
verify-push-backend/tests/access-token.test.js
verify-push-backend/tests/challenge-status.test.js
verify-push-backend/tests/create-challenge.test.js
verify-push-backend/tests/list-factors.test.js

Naming things is hard, SE advised we go back to Identity. Also fixing the markup location of where the `Edit Code` button will appear when Quick Deployed

Back to identity, move edit code macro

---

google-sheets/.env
google-sheets/README.md
google-sheets/assets/index.html
google-sheets/functions/check-sheets-config.js
google-sheets/functions/log-sms.protected.js
google-sheets/tests/check-sheets-config.test.js
google-sheets/tests/log-sms.test.js

This PR improves the Google Sheets template onboarding experience by including a step in `index.html` pointing the user towards the Google Cloud Console Sheets API permission page. It also makes environment variables easier to understand by giving them clearer names.

Improve Google Sheets Onboarding & Environment Variable Names

---

sms-broadcast/assets/index.html

Fix the link to messaging services

(fix) Update instructions for broadcast SMS setup

---

.eslintignore
airtable/functions/broadcast-sms.js
airtable/functions/save-sms.protected.js
airtable/tests/broadcast-sms.test.js
airtable/tests/save-sms.test.js
blocklist-call/functions/blocklist-call.js
blocklist-call/tests/blocklist-call.test.js
chat-token/functions/chat-token.js
chat-token/tests/chat-token.test.js
conference-caller-gated/tests/gated-conference.test.js
conference-pin/functions/conference-with-pin.protected.js
conference-pin/tests/conference-with-pin.test.js
conference-verify/functions/join-conference.protected.js
conference-verify/functions/verify-conference.protected.js
conference-verify/tests/join-conference.test.js
conference-verify/tests/verify-conference.test.js
conference/tests/conference.test.js
conversations/tests/generate-scoped-webhook.test.js
forward-call/functions/forward-call.js
forward-call/tests/forward-call.test.js
forward-message-mailgun/functions/forward-message-mailgun.protected.js
forward-message-multiple/functions/forward-message-multiple.js
forward-message-multiple/tests/forward-message-multiple.test.js
forward-message-sendgrid/functions/forward-message-sendgrid.protected.js
forward-message-sendgrid/tests/forward-message-sendgrid.test.js
forward-message-sparkpost/tests/forward-message-sparkpost.test.js
forward-message/functions/forward-message.js
forward-message/tests/forward-message.test.js
funlet-call-me/functions/funlet-call-me.js
funlet-call-me/tests/funlet-call-me.test.js

Fixes lint errors and warnings for 15 of the apps in the repository.

Cleanup Lint Errors [1/3]

---

verify/functions/check-verify.js
verify/tests/check-verify.test.js

Added a test condition to detect the issue too!

Fix: parameter destructuring bug in the Verify template, add test

---

package-lock.json
templates.json

fix(patient-appointment-management): templates.json

---

docs/static/v1/ce-paste-theme.css
verified-broadcast/assets/broadcast.html
verified-broadcast/assets/subscribe.html

Includes styling for `submit` buttons and an `intl-tel-input` compatibility class, taken from the `verified-broadcast` app.

Update ce-paste-theme to 1.1.0

---

patient-appointment-management/.env
patient-appointment-management/README.md
patient-appointment-management/assets/aws/cloudformation-stack-application.private.yml
patient-appointment-management/assets/aws/query_appointment_history.private.js
patient-appointment-management/assets/aws/send_appointment_reminders.private.js
patient-appointment-management/assets/controller.js
patient-appointment-management/assets/index.html
patient-appointment-management/assets/studio-flow-template.private.json
patient-appointment-management/functions/auth.private.js
patient-appointment-management/functions/deployment/check.js
patient-appointment-management/functions/deployment/deploy-aws-application.js
patient-appointment-management/functions/deployment/deploy-studio-flow.js
patient-appointment-management/functions/deployment/test-deployment.private.js
patient-appointment-management/functions/get-datetime-parts.protected.js
patient-appointment-management/functions/helpers.private.js
patient-appointment-management/functions/save-remind.protected.js
patient-appointment-management/tests/get-datetime-parts.test.js
patient-appointment-management/tests/helpers.test.js
patient-appointment-management/tool-make-service-editable.sh
patient-appointment-management/tool-package-studio-flow-template.sh
patient-appointment-management/tool-tail-function-logs.sh

public release candidate for patient-appointment-reminder.
reviews from initial PR can be found here: https://docs.google.com/document/d/1_NeUEo-YgSoZe7IqBYiz-9f03lcv7iQJhrU03ayG4zA/edit?ts=60db5a44

PAM public release candidate 1

---

patient-appointment-management/README.md
patient-appointment-management/assets/index.html

- [ x ] I ran `npm test` locally and it passed without errors.
- [ x ] I acknowledge that all my contributions will be made under the project's [license](../blob/main/LICENSE).

Pam documentation corrections

---

.github/CODEOWNERS

Defines a `CODEOWNERS` file to auto-assign reviews to the `@twilio-labs/function-reviewers` team.
Since `CODEOWNERS` doesn't support round-robin, all reviewers on the team will get notified when files change in the repo. It might make sense to split our reviewers team before this merges, into a core team responsible for the files in the base of the repo, the base `tests` directory, `docs`, and other ancillary items, and keep the `@twilio-labs/function-reviewers` team as a dedicated app review team.
Please review in light of the above; we can delay merging this until we get a better team structure in place to prevent anyone getting spammed with reviews.

feat(reviews): Add a CODEOWNERS file

---

patient-appointment-management/.env

Update .env for AWS_REGION

---

verify-push-backend/.env
verify-push-backend/assets/digest-message.private.js
verify-push-backend/assets/index.html
verify-push-backend/changelog.md
verify-push-backend/functions/access-token.js
verify-push-backend/functions/create-challenge.js
verify-push-backend/functions/list-factors.js
verify-push-backend/package.json
verify-push-backend/tests/access-token.test.js
verify-push-backend/tests/create-challenge.test.js
verify-push-backend/tests/digest-message.test.js
verify-push-backend/tests/list-factors.test.js

* Checking challenge status until its expiration time (5 minutes)
* Clearing factor list container before showing them
* Support for hidden details.
* Env variable to configure identity processing (hashing or not)
* Include React native link

Verify push backend improvements

---

test/all-templates.test.js

Adds a test that runs across all apps in the repo to ensure that any Function listed in a `.env` or `.env.example` file's `TWILIO_.*_WEBHOOK_URL` variables has `protected` visibility. This should be the case for almost every Quick Deploy app that follows our recommended structure -- the only exception is the old `hunt` app, which accesses its Twilio webhook from both Twilio and a browser context; that app is excluded from this test.

feat(tests): Test for webhook Function visibility

---

verify-totp/README.md

Remove Pilot warning now that TOTP is in public beta

---

.github/workflows/assign-reviewers.yml

Fix assign-reviewers workflow config

---

_helpers/meta-template/package.json
docs/CONTRIBUTING.md
package-lock.json
package.json

Adds the `runtime-helpers` library to the repo base `package.json` and to `meta-template`, and documents its usage in `CONTRIBUTING.md`.

Include and document runtime-helpers library

---

video/.env
video/README.md
video/assets/conference.js
video/functions/video-token.js
video/tests/video-token.test.js

Adds a `ROOM_NAME` configuration parameter to the `video` app, and passes the value of that variable back to the app UI via a new field returned from the `video-token` Function.

feat(video): Support for configurable room name

---

chat-token/functions/chat-token.js
chat-token/package.json
covid-vaccine-faq-bot/functions/auth.private.js
covid-vaccine-faq-bot/functions/setup.js
covid-vaccine-faq-bot/package.json
international-telephone-input/functions/lookup.js
international-telephone-input/package.json
lookup/functions/lookup.js
lookup/package.json
magic-links/functions/check-verify.js
magic-links/functions/start-verify.js
magic-links/package.json
sip-quickstart/assets/admin/shared.private.js
sip-quickstart/assets/admin/statuses.private.js
sip-quickstart/functions/admin/perform-action.js
sip-quickstart/package.json
sip-quickstart/tests/admin/perform-action.test.js
sip-quickstart/tests/admin/private/shared.test.js
sip-quickstart/tests/admin/private/statuses.test.js
stripe-sms-receipt/functions/send-sms-receipt.js
stripe-sms-receipt/package.json
sync-token/functions/sync-token.js
sync-token/package.json
vaccine-standby/functions/setup.js
vaccine-standby/package.json

Reverts twilio-labs/function-templates#305

Revert "Use runtime-helpers in apps (part 1/3)"

---

verified-broadcast/.env
verified-broadcast/README.md
verified-broadcast/assets/auth.private.js
verified-broadcast/functions/broadcast.js
verified-broadcast/package.json
verified-broadcast/tests/auth.test.js
verified-broadcast/tests/broadcast.test.js
verified-broadcast/tests/start-verify.test.js
verified-broadcast/tests/subscribe.test.js
verify-dashboard/functions/check-verify.js
verify-dashboard/functions/service-details.js
verify-dashboard/functions/start-verify.js
verify-dashboard/functions/status-verify.js
verify-dashboard/functions/update-verify.js
verify-dashboard/package.json
verify-push-backend/functions/access-token.js
verify-push-backend/functions/challenge-status.js
verify-push-backend/functions/create-challenge.js
verify-push-backend/functions/list-factors.js
verify-push-backend/package.json
verify-retry/functions/check-verify.js
verify-retry/functions/start-verify.js
verify-retry/package.json
video-token/functions/video-token.js
video-token/package.json

Reverts twilio-labs/function-templates#306

Revert "Use runtime-helpers in apps (part 2/3)"

---

verify-totp/functions/create-challenge.js
verify-totp/functions/create-factor.js
verify-totp/functions/verify-new-factor.js
verify-totp/package.json
verify/functions/check-verify.js
verify/functions/start-verify.js
verify/package.json
voice-client-javascript/assets/admin/shared.private.js
voice-client-javascript/assets/admin/statuses.private.js
voice-client-javascript/functions/admin/perform-action.js
voice-client-javascript/functions/voice-token.js
voice-client-javascript/package.json
voice-client-javascript/tests/admin/perform-action.test.js
voice-client-javascript/tests/admin/private/shared.test.js
voice-client-javascript/tests/admin/private/statuses.test.js
voice-javascript-sdk/assets/admin/shared.private.js
voice-javascript-sdk/assets/admin/statuses.private.js
voice-javascript-sdk/functions/admin/perform-action.js
voice-javascript-sdk/functions/voice-token.js
voice-javascript-sdk/package.json
voice-javascript-sdk/tests/admin/perform-action.test.js
voice-javascript-sdk/tests/admin/private/shared.test.js
voice-javascript-sdk/tests/admin/private/statuses.test.js

Reverts twilio-labs/function-templates#307

Revert "Use runtime-helpers in apps (part 3/3)"

---

package.json

Fix for failing unit tests

---

.eslintignore
.gitignore
_helpers/test-suite/cypress.js
_helpers/test-suite/e2e-config.js
_helpers/test-suite/index.js
_helpers/test-suite/serverless.js
docs/CONTRIBUTING.md
hello-world/cypress/integration/hello-world.spec.js
hello-world/cypress/plugins/index.js
hello-world/cypress/support/commands.js
hello-world/cypress/support/index.js
hello-world/e2e.js
hello-world/package.json
package-lock.json
package.json

This PR introduces a test suite so we can add Cypress E2E tests in each template.
It's not triggered in CI yet which will be a separate PR.

test: add e2e test suite with cypress

---

verify/assets/index.html

Move edit code macro in Verify template

---

verify/assets/index.html

Email selection accidentally eliminated in the refactor, adding it back!

Fix to selector to also use email

---

docs/USING_FUNCTIONS.md

Fixing a broken link to the `templates.json` file.

docs: update templates.json link

---

.github/workflows/nodejs.yml

Using Node.js 14 and also 16 in preparation of eventual release.

ci: update node.js versions for CI tests

---

.owners

chore: remove myfancypants from owners

---

frontline-quickstart/README.md
frontline-quickstart/assets/providers/customers.private.js
frontline-quickstart/functions/callbacks/crm.protected.js
frontline-quickstart/functions/callbacks/outgoing-conversation.protected.js
frontline-quickstart/functions/callbacks/routing.protected.js
frontline-quickstart/functions/callbacks/templates.protected.js
frontline-quickstart/functions/callbacks/twilio-conversations.protected.js

- Adding and unifying format of inline comments for better readability while also providing valuable links to documentation pieces

Frontline SLS Quickstart: improve inline comments + link to documentation

---

lookup/assets/index.html
lookup/changelog.md
lookup/functions/lookup.js
lookup/tests/lookup.test.js

Adds line type intelligence to the Lookup code exchange project. Merges v1 and v2 APIs until we are out of Beta and can fully replace the v1 API.

Add LTI to lookup template

---

verify-totp-sms/package.json

Explicitly add uuid as a dependency for totp-sms

---

verify-retry/functions/start-verify.js
verify-retry/tests/start-verify.test.js

Updates the lookup function to use the new V2 line type intelligence

Use Lookup V2 line type intelligence for verify retry function

---

international-telephone-input/functions/lookup.js
international-telephone-input/tests/lookup.test.js

A few minor changes:
* Replaces lookup call with v2. 
* Switches to async/await. 
* Improves testing

Use Lookup V2 for international telephone input, improve testing.

---

frontline-quickstart/README.md

chore(frontline-quickstart): remove link to old docs

---

.github/workflows/nodejs.yml

Fixes the extremely outdated CI config.

ci: update CI to use reasonable verisons of Node.js and npm

---

.github/workflows/assign-reviewers.yml

fixes the Assign Reviewers CI check by switching it to use GITHUB_TOKEN. Also updates the checkout action in this CI to v4.

ci: fix asssign reviewers

---

package.json

updates the `prepare` script for npm to what Husky 9 now uses. Ref: https://github.com/typicode/husky/releases/tag/v9.0.1

chore: update husky prepare command

---

README.md
verify-prefill/.env.example
verify-prefill/README.md
verify-prefill/functions/blank.js
verify-prefill/functions/fetch-user-data.js
verify-prefill/functions/send-otp.js
verify-prefill/functions/verify-otp.js
verify-prefill/package.json
verify-prefill/tests/blank.test.js
verify-prefill/tests/fetch-user-data.test.js
verify-prefill/tests/send-otp.test.js
verify-prefill/tests/verify-otp.test.js

Adds tests to Verify Prefill app.

Add tests for verify prefill

---

blank/functions/blank.js
forward-call/functions/forward-call.protected.js
package-lock.json

Contains updates to the forward-call template with an example of the comment standard we are looking for 
Contains updates to the blank template with guidelines for the comment standard we are looking for

Function Templates Comment Example and Template

---

ai-assistants-samples/.env.example
ai-assistants-samples/assets/index.html

Removing the need to specify ACCOUNT_SID and AUTH_TOKEN as these are auto inserted by Twilio Functions. Also marking all variables as not required as none of them are required to deploy.

fix(ai-assistants-samples): remove unnecessary env variables

---

ai-assistants-samples/assets/index.html

fix(ai-assistants-samples): fix URL typos

---

hello-messaging/functions/hello-messaging.protected.js

Added comments to the code for better readability and understanding

CodeExchange update - Hello Messaging template

---

passkeys-backend/.env.example
passkeys-backend/README.md
passkeys-backend/package.json

* Adds axios as a dependency
* Sets default API_URL
* improves README

Passkeys backend improvements/fixes for code exchange

---

templates.json

removes the two deleted templates I was able to find still in `templates.json`
N/A

fix: remove deleted templates from templates.json

---

mcp-server/README.md
mcp-server/assets/index.html
templates.json

Updating README and project terminology.

MCP Server: Documentation Update

---

list-numbers/.env

Modifying the placeholder text for the Password variable to be more intuitive.

Better password placeholder text
