twilio-labs/function-templates

templates.json
=> Fix typo which popped up in the CLI function template overview

README.md
the link to the Code of Conduct was missing the file extension, resulting in a 404 error when following the link. I added .md et voila. 
=> fix README link to Code of Conduct

voicemail/tests/voicemail.test.js
Fixes deprecation notice from Moment.js: https://momentjs.com/guides/#/warnings/js-date/.
Is there anything wrong with using this date format instead? This is just for the tests and mocking the current time, right?
=> chore(voicemail): corrected date format

video-token/.env
This is a very minor fix to the .env file when running the `video-token` function. 
This addition adds a stub for SID to the .env file to allow the function to run via `twilio serverless:start`. 
Prior to this the stackTrace error is `Error: keySid is required`.
=> fix(video-token): add to .env to add stub for SID

_helpers/meta-template/README.md
When I copied the verify template to become the meta template I missed updating the folder name after calling `serverless:init`
=> fix(meta-template): update init instructions

sip-quickstart/assets/admin/actions.private.js
New users are temporarily limited to 1 concurrent API request. Previously this code made use of asynchronous activity for speed.
=> fix(sip-quickstart): limit to only 1 concurrent API request

_helpers/add-template.js, _helpers/meta-template/assets/index.html, docs/CONTRIBUTING.md
This adds a new index.html template that we should use in every function template. It helps explain what last steps to do to set up and test your application. 
The current CSS makes use of milligram. I'll replace that once we have an equivalent that's powered by Paste.
=> feat(meta): add index.html to template base

blocklist-call/functions/blocklist-call.js
URL does not support POST, so it was returning 404 page, which looked like invalid TwiML.
=> fix(blocklist-call): change http method for redirect

blocklist-call/functions/blocklist-call.js, sip-quickstart/assets/admin/index.html, sip-quickstart/assets/index.html, sip-quickstart/functions/sip-configuration.js
The /index.html route on SIP Quickstart requires initialization first. This change alerts and redirects.
=> fix(templates/sip-quickstart) redirect to admin page prior to init

docs/CONTRIBUTING.md
This fixes a small formatting error in CONTRIBUTING.md.
Using `**bold**` to hightlight a part of a URL doesn't work in GH-flavored markdown, apparently.
=> docs: Fixing a little formatting nit

sms-broadcast/.env, sms-broadcast/README.md, sms-broadcast/assets/index.html, sms-broadcast/functions/broadcast.protected.js, sms-broadcast/package.json, sms-broadcast/tests/broadcast.test.js, templates.json
This adds the [SMS Broadcast template from Twilio.org's toolkit](https://github.com/Twilio-org/toolkit/blob/master/docs/broadcast.md).
=> Adds SMS Broadcast function from Twilio.org toolkit

docs/CONTRIBUTING.md, test/all-templates.test.js
Adds a new Jest test that runs against each function template and ensures that each one has a `.env` file, to prevent deployment errors caused by the file being missing. This test will run both locally and on the CI to catch cases where `.env` exists locally, but is accidentally not committed.
The new test lives in test/all-templates.test.js, which uses FileHound to collect a list of repo subdirectories with a package.json, and generates Jest tests for each one. An individual test was created per `.env` file because it had a minimal impact on `npm test` performance (on the order of a 0.15 second runtime increase from a hot cache), but allowed for much more expressive failed assertion messages in case of a failed test.
=> fest(testing): Add a Jest test for missing template .env files

masked-number/.env, masked-number/README.md, masked-number/assets/index.html, masked-number/functions/relay-sms.protected.js, masked-number/package.json, masked-number/tests/relay-sms.test.js, templates.json
The masked-number template relays SMS messages to and from a personal
phone number, via a Twilio number. This is based on the code in the blog
post at
https://www.twilio.com/blog/sms-forwarding-and-responding-using-twilio-and-javascript
=> feat(templates): create masked-number template

international-telephone-input/README.md, international-telephone-input/assets/index.html, international-telephone-input/assets/styles.css, international-telephone-input/functions/lookup.js, international-telephone-input/package.json, international-telephone-input/tests/lookup.test.js, templates.json
Show off how to use the intl-tel-input library in combination with Lookup to build international input fields and detect invalid phone numbers.
Demo: https://telinput-4826-dev.twil.io/index.html
Side note - this project doesn't require any additional environment variables, but the tests failed when I didn't add a .env file, so I left it empty.
=> feat(templates): Add international tel input example template

verify/functions/start-verify.js, verify/tests/start-verify.test.js
A small safety measure to help protect against [toll fraud](https://www.twilio.com/docs/verify/preventing-toll-fraud). Sorry for the larger diff, my linter finally works.
=> Disable calls by default for the verify template

vaccine-standby/README.md, vaccine-standby/assets/index.html, vaccine-standby/functions/check-existing-flow.js, vaccine-standby/functions/get-studio-executions.js
- Add disclaimer about contacting us before running in production
- Make clear that app does not contain functionality for notifications
- Remove unnecessary use of fetching serverless environment to read `.env` variables
=> fix(vaccine-standby): clarify language, use context for env

_helpers/meta-template/assets/index.html, forward-call/assets/index.html, forward-message-mailgun/assets/index.html, forward-message-multiple/assets/index.html, forward-message-sendgrid/assets/index.html, forward-message-sparkpost/assets/index.html, forward-message/assets/index.html
Updates `meta-template` (which `npm run new-template` copies as the basis of new apps) and 5 apps to use the redesigned `index.html`. The apps updated are:
- `forward-message-mailgun`
- `forward-message-multiple`
- `forward-message-sendgrid`
- `forward-message-sparkpost`
- `forward-call`
=> feat(index.html): Migrate meta-template and 5 apps

conference-caller-gated/assets/index.html, conference-pin/assets/index.html, conference-verify/assets/index.html, conference/assets/index.html
This PR migrates 4 apps to use the redesigned `index.html`:
- `conference`
- `conference-verify`
- `conference-pin`
- `conference-caller-gated`
=> feat(index.html) Second batch of migrations

airtable/assets/index.html, sms-broadcast/assets/index.html, stripe-payment-link-sms/assets/index.html, stripe-sms-receipt/assets/index.html
Migrates a third batch of apps to use redesigned `index.html` files:
- `airtable`
- `sms-broadcast`
- `stripe-payment-link-sms`
- `stripe-sms-receipt`
=> feat(index.html): Migrate third batch of apps

blocklist-call/assets/index.html, chat-token/assets/index.html, hello-messaging/assets/index.html, hello-voice/assets/index.html, hello-world/assets/index.html
Migrates five more apps to use the `index.html` redesign:
* `blocklist-call`
* `chat-token`
* `hello-messaging`
* `hello-voice`
* `hello-world`
=> feat(index.html): Fourth batch of migrations

env-variables.manifest.json, package-lock.json, package.json
This PR adds the latest version of the `configure-env` parser that adds the support for `file(json)` and the respective `contentKey` properties to `.env` files.
=> feat(meta): add file type to env manifest

funlet-find-me/functions/funlet-find-me.js, funlet-find-me/tests/funlet-find-me.test.js
Some of the changes were done by Prettier. The main changes I implemented:
- added a `getBaseUrl()` function that constructs the full base URL from the `context` since the relative `.` URL turned out to be flaky.
- adjust the appending of phone numbers in subsequent URLs to contain the index to mimic the original URL structure. Example: `PhoneNumbers[0]` instead of `PhoneNumbers[]`. 
- reformat `if` statement in main `handler` function to be a bit more readible
- change logic of `findMeStage4` to mimic original PHP code (fixed the main issue)
- add a `<Say>Connecting</Say>` to the `findMeStage3` if the user pressed a digit.
=> fix(funlet-find-me): adjust logic to continue hunting

google-sheets/.env, google-sheets/README.md, google-sheets/assets/auth.private.json, google-sheets/assets/index.html, google-sheets/functions/check-sheets-config.js, google-sheets/functions/log-sms.js, google-sheets/functions/log-sms.protected.js, google-sheets/package.json, google-sheets/tests/auth.test.json, google-sheets/tests/check-sheets-config.test.js, google-sheets/tests/log-sms.test.js, package-lock.json, package.json, templates.json
Adds the google-sheets template, which logs incoming SMS numbers and text bodies to a Google Sheets spreadsheet.
This is a candidate for a Quick Deploy function, but there are a couple of setup complexities instituted by Google's API:
- The user must create a Google Cloud service account, generate a private key file for it, and add that file to the function's assets. The service account is a strict requirement of how Google handles OAuth permissions. There may be an undocumented way to pull authentication information from an environment variable instead of a file, but this may not be a stable part of Google's API.
- The spreadsheet being logged into is created by the user (which saves a lot of document management complexity for this code example) and then shared with the service account's …
=> feat(templates): Create a template Google Sheets integration

http-redirect/assets/index.html, hunt/assets/index.html, json-webhook/assets/index.html, masked-number/assets/index.html
Migrates a fifth batch of apps to use redesigned `index.html` files. The four apps in this PR are:
- `http-redirect`
- `hunt`
- `json-webhook`
- `masked-number`
=> feat(index.html): Fifth batch of migrations

video-token/assets/index.html, voice-ivr/assets/index.html
Migrates a sixth batch of apps to use the `index.html` redesign. The two apps included in this PR are:
- `video-token`
- `voice-ivr`
=> feat(index.html): Sixth batch of migrations

sync-token/assets/index.html, temp-storage/assets/index.html
This is the seventh batch of apps migrated to the `index.html` redesign. The two apps included are:
- `sync-token`
- `temp-storage`
=> feat(index.html): Seventh batch of migrations

sms-broadcast/.env, sms-broadcast/README.md, sms-broadcast/assets/index.html
Updates the docs for `sms-broadcast` to reflect the modern Twilio Console UI. I couldn't find a stable URL that links directly to the Twilio Console page for the Notify service, so let me know if there's a good option to link straight to that from `index.html`.
=> feat(docs): Update sms-broadcast docs

airtable/package.json, conversations/package.json, forward-message-mailgun/functions/forward-message-mailgun.protected.js, forward-message-mailgun/package.json, forward-message-mailgun/tests/forward-message-mailgun.test.js, international-telephone-input/package.json, magic-links/package.json, package-lock.json, package.json, sip-quickstart/package.json, vaccine-standby/package.json, verify-dashboard/package.json, verify/package.json, voice-client-javascript/package.json
`mailgun-js` is no longer the officially supported sdk from Mailgun. It now uses `mailgun.js` instead.
This updates the dependency to use the official version and any updates required to accommodate changes in its usage.
There were a few thousand found vulnerabilities in the previous dependencies versions for all of function-templates, so `npm audit fix` was run in order to bring the total found issues down to 0
=> fix: update deps and move to mailgun.js for mailgun template

funlet-call-me/.env, funlet-call-me/assets/index.html, funlet-echo/.env, funlet-echo/assets/index.html, funlet-find-me/.env, funlet-find-me/assets/index.html, funlet-find-me/functions/funlet-find-me.js, funlet-forward/.env, funlet-forward/assets/index.html, funlet-simple-menu/.env, funlet-simple-menu/assets/index.html, funlet-simple-message/.env, funlet-simple-message/assets/index.html, funlet-simulring/.env, funlet-simulring/assets/index.html, funlet-simulring/functions/funlet-simulring.js, funlet-whisper/.env, funlet-whisper/assets/index.html, test/all-templates.test.js
This PR makes the `funlet-*` templates Quick Deployable. For most funlets, this just involves writing an `index.html` and mapping the funlet's configuration variables to `.env` variables. `funlet-find-me` and `funlet-simulring` needed slight modifications to parse an environment variable as a comma-separated list. `funlet-whisper` is an odd case; I couldn't quite parse out what it's supposed to do in full, and it's a port of an undocumented Twimlet.
=> Make Funlets Quick Deployable

.gitignore, _helpers/generate-env-variable-manifest.js, _helpers/meta-template/README.md, docs/CONTRIBUTING.md, test/all-templates.test.js
When generating the template manifest, and during testing, `.env.example` will now be looked up, followed by `.env` if that file doesn't exist. This is to improve DX around secrets: `.env.example` will contain the skeletons and defaults that `.env` files do now, and developers deploying function templates will place secrets in a `.env` file based on that skeleton that should never be in source control. This PR preserves existing behavior around function templates that have a `.env` file and no `.env.example`, for backwards compatibility. It also updates documentation to reflect how `.env.example` should be used.
=> feat(.env): Look for .env.example and update docs

package-lock.json, templates.json, verified-broadcast/.env, verified-broadcast/README.md, verified-broadcast/assets/broadcast.html, verified-broadcast/assets/index.html, verified-broadcast/assets/subscribe.html, verified-broadcast/functions/broadcast.js, verified-broadcast/functions/start-verify.js, verified-broadcast/functions/subscribe.js, verified-broadcast/package.json, verified-broadcast/tests/broadcast.test.js, verified-broadcast/tests/start-verify.test.js, verified-broadcast/tests/subscribe.test.js
A variation of the `sms-broadcast` template that uses a web interface for subscribing.
There's a lot of duplicate code in `subscribe.js` and `broadcast.js` (since they both chain the verification check functionality) that I'm not sure if there's a good way to break out (or if it's worth it) - any advice here would be appreciated!
[Live demo](https://verified-broadcast-6272-dev.twil.io/index.html)
=> feat(templates): Add verified broadcast function template

covid-vaccine-faq-bot/.env, covid-vaccine-faq-bot/README.md, covid-vaccine-faq-bot/assets/client.js, covid-vaccine-faq-bot/assets/service-account-key.private.json, env-variables.manifest.json
- Fix GCP service account key file upload by adding a placeholder file in the `assets` directory for CodeExchange to populate with JSON
- Fix reference to Twilio phone number in the UI changed as a result of linting (`phone_number` --> `phoneNumber`)
- Make Dialogflow language code env variable optional
- Add some language to the `.env` and `README` files to help a user set environment variables correctly
=> Fixes/Polishes for COVID vaccine hesitancy chatbot template

README.md, templates.json, verify-retry/.env, verify-retry/README.md, verify-retry/assets/index.html, verify-retry/assets/utils.private.js, verify-retry/functions/check-verify.js, verify-retry/functions/start-verify.js, verify-retry/package.json, verify-retry/tests/check-verify.test.js, verify-retry/tests/start-verify.test.js
This project builds on the OTP verification but focuses on the UI/UX best practices around retry logic and voice fallback. There are more details in this blog post: https://www.twilio.com/blog/best-practices-retry-logic-sms-2fa
This is my first time using the async/await pattern for a function template which cleaned up the code and made testing easier, but let me know if anything looks off.
Live demo: https://verify-retry-6659-dev.twil.io/index.html
=> feat(templates): add verify retry logic UI template

package.json
Sets our Jest test coverage minimum to 60% for statements and branches, for any Javascript file under an app's `functions` directory (or any Javascript files in subdirectories under that). Two apps are filtered out of test coverage because they do not hit these minimums: `video` and `patient-appointment-management`. This was done in `coveragePathIgnorePatterns` instead of adding a glob to `coverageThreshold` due to a Jest bug that causes unexpected behavior when more than one glob matches a pattern. This check should also automatically catch files with no tests which do not appear in the default coverage report.
=> Enforce test coverage minimums

verified-broadcast/assets/index.html, verified-broadcast/assets/setup.private.js
This PR fixes two issues found when deploying the template using Quick Deploy:
1. Current Quick Deploy will set empty optional variables as `""`. While this should be fixed in the system, this works as a workaround in the meantime.
2. For some reason in the deployed Twilio Functions the `service.phoneNumbers.list` call was throwing an error so I changed it to a more explicit call.
This PR also adjusts the usage steps since they are no longer relevant.
=> fix(verified-broadcast): adjust usage steps and setup logic

caller-id-forwarding/.env, caller-id-forwarding/.owners, caller-id-forwarding/README.md, caller-id-forwarding/assets/index.html, caller-id-forwarding/changelog.md, caller-id-forwarding/functions/forward-call.protected.js, caller-id-forwarding/package.json, caller-id-forwarding/tests/forward-call.test.js, templates.json
Expansion of the call forwarding template. Before forwarding, looks up the incoming phone number and sends an SMS with caller id-like information to the forwarding number.
=> (feat: templates): add Caller ID + Call Forwarding

contact-form/assets/index.html, contact-form/functions/send-email.js
1. Front end: if a form submission fails due to a 500 error, the submit button previously stayed disabled. This adds a finally block to re-enable the button after everything else has happened.
2. Back end: two Twilio.Response objects were initialized when only one is needed.
=> fix(contact-form): two small mistakes

experimental-flex-dialpad/assets/helpers/setup.private.js
Quick Deploy sets unconfigured empty variables to the value `""` which means it's technically not empty. This change adds that scenario to the check if a variable is empty.
=> fix(experimental-flex-dialpad): change env check for empty case

README.md
Added a warning message to README about Node18 release as this may effect code snippets present in this repository. 
https://github.com/twilio-labs/function-templates/pull/478
=> Update README.md with Node 18 Warning

forward-message-multiple/functions/forward-message-multiple.protected.js, forward-message/functions/forward-message.protected.js
Parameters passed into `twiml.message` were backwards, causing the message being forwarded back to the sender and not to the number specified in the `to:` attibute. Placing the verb attributes before the message body fixed the issue. 
Using [docs](https://www.twilio.com/docs/messaging/twiml/message#messagestatus-reporting) as reference.
=> Parameters passed to twiml.message were backwards. 

.github/workflows/nodejs.yml
cleans up the CI runner that builds, tests, lints, and checks formatting on everything. Makes the steps in the Actions UI a bit more tidy/independent, and removes some unnecessary cruft.
=> ci: clean up the Node.js CI GitHub Action

verify/functions/check-verify.js, verify/functions/start-verify.js, verify/package.json, verify/tests/start-verify.test.js
…nsole, cleaned up code
Worked with @rishabkumar7 to update this project
* bumped twilio-node dependency
* delegated channel enabling back to console
* cleaned up code
=> Cleaning up OTP project for code exchange

magic-links/assets/email-template.html, magic-links/assets/index.html, magic-links/assets/verify.html, magic-links/functions/check-verify.js, magic-links/functions/start-verify.js, magic-links/tests/check-verify.test.js, magic-links/tests/start-verify.test.js
Brings in the paste theme as well.
=> Upgrades to verify v2, improves testing

ai-assistants-samples/.env.example, ai-assistants-samples/.owners, ai-assistants-samples/CHANGELOG.md, ai-assistants-samples/README.md, ai-assistants-samples/assets/index.html, ai-assistants-samples/assets/utils.private.js, ai-assistants-samples/functions/channels/conversations/flex-webchat.protected.js, ai-assistants-samples/functions/channels/conversations/messageAdded.protected.js, ai-assistants-samples/functions/channels/conversations/response.js, ai-assistants-samples/functions/channels/messaging/incoming.protected.js, ai-assistants-samples/functions/channels/messaging/response.js, ai-assistants-samples/functions/tools/flex-handover.js, ai-assistants-samples/functions/tools/google-maps.js, ai-assistants-samples/functions/tools/internet-search.js, ai-assistants-samples/functions/tools/studio-handover.js, ai-assistants-samples/functions/tools/ui-tools.js, ai-assistants-samples/package.json, ai-assistants-samples/tests/channels/conversations/flex-webchat.test.js, ai-assistants-samples/tests/channels/conversations/messageAdded.test.js, ai-assistants-samples/tests/channels/conversations/response.test.js, ai-assistants-samples/tests/channels/messaging/incoming.test.js, ai-assistants-samples/tests/channels/messaging/response.test.js, ai-assistants-samples/tests/tools/flex-handover.test.js, ai-assistants-samples/tests/tools/google-maps.test.js, ai-assistants-samples/tests/tools/studio-handover.test.js, ai-assistants-samples/tests/tools/ui-tools.test.js, package-lock.json, package.json, templates.json
This PR is largely a clone of github.com/twilio-labs/ai-assistants-samples where most of the development is happening and this is purely to bring it over for Quick Deploy support. This currently has no automated tests which I will add next week but we would like to get this deployed asap for a Buildathon on Monday.
=> feat(ai-assistants-samples): add new template

lookup/assets/index.html, lookup/assets/styles.css, lookup/changelog.md, lookup/functions/lookup.js, lookup/package.json, lookup/tests/lookup.test.js
👀  [Live example](https://lookup-sample-9681-dev.twil.io/index.html)
Migrate to Lookup V2 for all packages
Adds new packages only available in V2:
* [SMS Pumping Risk](https://www.twilio.com/docs/lookup/v2-api/sms-pumping-risk)
* [SIM Swap](https://www.twilio.com/docs/lookup/v2-api/sim-swap)
* [Call Forwarding](https://www.twilio.com/docs/lookup/v2-api/call-forwarding)
* [Line Status](https://www.twilio.com/docs/lookup/v2-api/line-status)
Still to do but not necessary for an MVP upgrade:
* [Use test credentials and magic numbers](https://www.twilio.com/docs/lookup/magic-numbers-for-lookup)
* Support Identity Match & Reassigned Number with additional fields
=> Updates lookup

forward-call/README.md, forward-call/assets/index.html
- Update and add additional links to Twilio docs
- Update language and phrasing for clarity
=> Update forward call

voicemail/README.md, voicemail/changelog.md, voicemail/functions/recording.js, voicemail/functions/voicemail.protected.js, voicemail/package.json
- Documents code and adds comments to the recording and voicemail functions using the template comment standard
- Updates a helper function name for clarity
=> Update voicemail template

ai-assistants-samples/assets/utils.private.js, ai-assistants-samples/functions/channels/conversations/flex-webchat.protected.js, ai-assistants-samples/functions/channels/conversations/messageAdded.protected.js, ai-assistants-samples/functions/channels/messaging/incoming.protected.js
We are moving to a new API structure for AI Assistants. This is moving the sample code to the same one
=> fix(ai-assistants-samples): move to new API structure

verify-prefill/assets/script.js
The team improved API latency so we can fetch more frequently. FYI @aricday
=> Decrease fetch timeout with API improvements

passkeys-backend/functions/registration/start.js, passkeys-backend/tests/registration-start.test.js
Deploying from the [CodeExchange](https://www.twilio.com/code-exchange/verify-passkeys) leaves an "empty string" without stripping the quotes. This change handles that edge case.
=> Add error handling for optional field when left empty

mcp-server/.env.example, mcp-server/.owners, mcp-server/CHANGELOG.md, mcp-server/README.md, mcp-server/assets/index.html, mcp-server/functions/mcp.protected.js, mcp-server/functions/req.private.js, mcp-server/functions/res.private.js, mcp-server/functions/server.private.js, mcp-server/package.json, package-lock.json, package.json, templates.json
Adds the ability to deploy an MCP server to Functions for Twilio API tools
=> MCP Server template

passkeys-backend/assets/index.html, passkeys-backend/functions/registration/start.js, passkeys-backend/tests/registration-start.test.js
The code was ignoring the country code, this fix sends the E.164 formatted number to the backend and fixes some of the formatting.
Main change is here: https://github.com/twilio-labs/function-templates/pull/595/files#diff-1337e4517fafaf1ecc4e4ba959494bf3e9b59953f244d178e7c0842119666abfR281
The rest is formatting updates!
=> Use E.164 format by default for phone numbers

email-events-sms/README.md
Add additional resources section to the readme of email-events-sms
=> feat(email-events-sms): update README to add additional resources
